version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=iba1234
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 20 1 --loglevel warning --requirepass iba1234
  #   volumes:
  #     - ecom-cache:/data

  # backend:
  #   build:
  #     context: ../ecommerce-backend
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ".env"
  #   deploy:
  #     mode: replicated
  #     replicas: 1

volumes:
  postgres:
    driver: local
  ecom-cache:
    driver: local